trigger:
- main

pool: 
    vmImage: ubuntu-latest

variables:
    buildConfiguration: 'Release'

steps:
- script: dotnet --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'